// examples/with-solid/src/pages/About.tsx
import { createMemo, Show } from 'solid-js'
import pages from 'virtual:content/pages'

export function About() {
  const about = createMemo(() => pages.find((page) => page.contentSlug === 'pages/about'))

  return (
    <Show when={about()} fallback={<p>About page not found.</p>}>
      {(p) => (
        <div>
          <h1>{p().frontmatter.title}</h1>
          <div class="prose" innerHTML={p().html} />
        </div>
      )}
    </Show>
  )
}

// examples/with-react/src/pages/About.tsx
import pages from 'virtual:content/pages'

export function About() {
  const about = pages.find((page) => page.contentSlug === 'pages/about')

  if (!about) {
    return (
      <div>
        <h1>About</h1>
        <p>About page content not found.</p>
      </div>
    )
  }

  return (
    <article>
      <div className="prose" dangerouslySetInnerHTML={{ __html: about.html }} />
    </article>
  )
}
