// examples/with-solid/src/App.tsx
import { createMemo, createSignal, onCleanup } from 'solid-js'
import { Layout } from './components/Layout'
import { About } from './pages/About'
import { Home } from './pages/Home'
import { Post } from './pages/Post'

function getHash(): string {
  return window.location.hash.slice(1) || '/'
}

export function App() {
  const [hash, setHash] = createSignal(getHash())

  const onHashChange = () => setHash(getHash())
  window.addEventListener('hashchange', onHashChange)
  onCleanup(() => window.removeEventListener('hashchange', onHashChange))

  const route = createMemo(() => {
    const h = hash()
    if (h === '/' || h === '') return { page: 'home' as const }
    if (h === '/about') return { page: 'about' as const }
    const postMatch = h.match(/^\/posts\/(.+)$/)
    if (postMatch) return { page: 'post' as const, slug: postMatch[1] }
    return { page: 'home' as const }
  })

  return (
    <Layout>
      {(() => {
        const r = route()
        switch (r.page) {
          case 'home':
            return <Home />
          case 'post':
            return <Post slug={r.slug!} />
          case 'about':
            return <About />
        }
      })()}
    </Layout>
  )
}

// examples/with-react/src/App.tsx
import { useEffect, useState } from 'react'
import { Layout } from './components/Layout'
import { About } from './pages/About'
import { Home } from './pages/Home'
import { Post } from './pages/Post'

type Route = { page: 'home' } | { page: 'post'; slug: string } | { page: 'about' }

function parseHash(hash: string): Route {
  const path = hash.replace(/^#\/?/, '')

  if (path === '' || path === '/') {
    return { page: 'home' }
  }

  if (path === 'about') {
    return { page: 'about' }
  }

  const postMatch = path.match(/^posts\/(.+)$/)
  if (postMatch) {
    return { page: 'post', slug: postMatch[1] }
  }

  return { page: 'home' }
}

function CurrentPage({ route }: { route: Route }) {
  switch (route.page) {
    case 'home':
      return <Home />
    case 'post':
      return <Post slug={route.slug} />
    case 'about':
      return <About />
  }
}

export function App() {
  const [route, setRoute] = useState<Route>(() => parseHash(window.location.hash))

  useEffect(() => {
    function onHashChange() {
      setRoute(parseHash(window.location.hash))
    }
    window.addEventListener('hashchange', onHashChange)
    return () => window.removeEventListener('hashchange', onHashChange)
  }, [])

  return (
    <Layout>
      <CurrentPage route={route} />
    </Layout>
  )
}
