// examples/with-svelte/src/App.svelte
<script lang="ts">
  import Layout from './components/Layout.svelte'
  import Home from './pages/Home.svelte'
  import Post from './pages/Post.svelte'
  import About from './pages/About.svelte'

  let hash = $state(window.location.hash || '#/')

  function onHashChange() {
    hash = window.location.hash || '#/'
  }

  $effect(() => {
    window.addEventListener('hashchange', onHashChange,)
    return () => window.removeEventListener('hashchange', onHashChange,)
  })

  function parseRoute(h: string,): { page: string; slug?: string } {
    const path = h.replace(/^#\/?/, '',)
    if (!path || path === '/') {
      return { page: 'home', }
    }
    if (path === 'about') {
      return { page: 'about', }
    }
    const postMatch = path.match(/^posts\/(.+)$/,)
    if (postMatch) {
      return { page: 'post', slug: postMatch[1], }
    }
    return { page: 'home', }
  }

  let route = $derived(parseRoute(hash,))
</script>

<Layout>
  {#if route.page === 'home'}
    <Home />
  {:else if route.page === 'post' && route.slug}
    <Post slug={route.slug} />
  {:else if route.page === 'about'}
    <About />
  {:else}
    <Home />
  {/if}
</Layout>

// examples/with-react/src/App.tsx
import { useEffect, useState } from 'react'
import { Layout } from './components/Layout'
import { About } from './pages/About'
import { Home } from './pages/Home'
import { Post } from './pages/Post'

type Route = { page: 'home' } | { page: 'post'; slug: string } | { page: 'about' }

function parseHash(hash: string): Route {
  const path = hash.replace(/^#\/?/, '')

  if (path === '' || path === '/') {
    return { page: 'home' }
  }

  if (path === 'about') {
    return { page: 'about' }
  }

  const postMatch = path.match(/^posts\/(.+)$/)
  if (postMatch) {
    return { page: 'post', slug: postMatch[1] }
  }

  return { page: 'home' }
}

function CurrentPage({ route }: { route: Route }) {
  switch (route.page) {
    case 'home':
      return <Home />
    case 'post':
      return <Post slug={route.slug} />
    case 'about':
      return <About />
  }
}

export function App() {
  const [route, setRoute] = useState<Route>(() => parseHash(window.location.hash))

  useEffect(() => {
    function onHashChange() {
      setRoute(parseHash(window.location.hash))
    }
    window.addEventListener('hashchange', onHashChange)
    return () => window.removeEventListener('hashchange', onHashChange)
  }, [])

  return (
    <Layout>
      <CurrentPage route={route} />
    </Layout>
  )
}
