// examples/with-solid/src/main.tsx
import { render } from 'solid-js/web'
import styles from 'virtual:content/styles'
import { App } from './App'

// Inject content styles
const styleEl = document.createElement('style')
styleEl.textContent = styles
document.head.appendChild(styleEl)

const root = document.getElementById('root')
if (root) {
  render(() => <App />, root)
}

// examples/with-react/src/main.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import css from 'virtual:content/styles'
import { App } from './App'

// Inject content runtime styles
const style = document.createElement('style')
style.textContent = css
document.head.appendChild(style)

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
